name: expenses_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.63.0
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0+1
  flutter_side_menu: ^0.4.0
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner:
  mobx_codegen:

flutter:
  uses-material-design: true
  assets:
    - assets/images/